language: node_js

node_js:
  - "7"

cache: yarn

sudo: required

services:
  - docker

before_install:
  - docker run -d -p 27017:27017 mongo
  - docker ps -a

script:
  - yarn run test:ci

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build -t "$DOCKER_REPO":web -f docker/web/Dockerfile .;
    docker build -t "$DOCKER_REPO":worker -f docker/worker/Dockerfile .;
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push "$DOCKER_REPO";
    fi
