# this compose file contains overrides for docker-compose.yml for use in dev

version: '3'
services:
  web:
    environment:
      LOG_LEVEL: debug
      NODE_ENV: development
      HOST: modlogs.local:4241
    volumes:
      - ../src:/app/src
      - ../next.config.js:/app/next.config.js
      - .:/app/docker
      - /tmp/modlogs/.next:/app/src/.next
    entrypoint: yarn dev

  login:
    environment:
      LW_SUBDOMAIN: login.modlogs.local:4241

  mongo:
    volumes:
      - ../mongo/data:/data
      - ../mongo/data/db:/data/db
      - ../mongo/data/configdb:/data/configdb

  redis:
    volumes:
      - ../redis:/data

  nginx:
    image: vitosamson/modlogs:nginx-dev
    ports:
      - 4241:443
